name = "aiken-lang/aiken-tutorial"
version = "0.0.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/aiken-tutorial'"

[repository]
user = "aiken-lang"
project = "aiken-tutorial"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
